openapi: 3.0.1
info:
  title: Widget API
  description: "Widget Resource API"
  version: 0.0.1
  contact:
    name: Mark T
    email: "mark.turner0@gmail.com"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: http://localhost:8080
    description: Localhost
    variables:
      basePath:
        default: v1
components:
  schemas:
    GeneralError:
      type: object
      properties:
        message:
          type: string
    WidgetCreate:
      type: object
      required:
        - x
        - y
      properties:
        x:
          type: integer
          format: int32
        y:
          type: integer
          format: int32
        z:
          type: integer
          format: int32
    Widget:
      type: object
      required:
        - id
        - x
        - y
      properties:
        id:
          type: integer
          format: int32
        x:
          type: integer
          format: int32
        y:
          type: integer
          format: int32
        z:
          type: integer
          format: int32
        modified:
          type: string
          format: date-time
  parameters:
    idParam:
      name: id
      in: path
      description: ID in path
      required: true
      schema:
        type: integer
        format: int32
    skipParam:
      name: skip
      in: query
      description: number of items to skip
      required: false
      schema:
        type: integer
        format: int32
    limitParam:
      name: limit
      in: query
      description: max records to return
      required: true
      schema:
        type: integer
        format: int32
  responses:
    NotFound:
      description: Resource Not found.
    BadRequest:
      description: Bad Request.
    GeneralError:
      description: General Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GeneralError'
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic

paths:
  /widgets:
    get:
      description: Returns all widgets
      parameters:
        - $ref: "#/components/parameters/skipParam"
        - $ref: "#/components/parameters/limitParam"
      responses:
        '200':
          description: A list of widgets.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Widget'
        '404':
          $ref: '#/components/responses/NotFound'
        default:
          $ref: '#/components/responses/GeneralError'
    post:
      description: Create a widget.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WidgetCreate'
      responses:
        '200':
          description: The new widget.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Widget'
        default:
          $ref: '#/components/responses/GeneralError'

  /widgets/{id}:
    parameters:
      - $ref: '#/components/parameters/idParam'
    get:
      description: Return a widget.
      responses:
        '200':
          description: The requested widget.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Widget'
        '404':
          $ref: '#/components/responses/NotFound'
        default:
          $ref: '#/components/responses/GeneralError'
    put:
      description: Update a widget
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WidgetCreate'
      responses:
        '200':
          description: The updated widget.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Widget'
        '404':
          $ref: '#/components/responses/NotFound'
        default:
          $ref: '#/components/responses/GeneralError'
    delete:
      description: Delete a widget
      responses:
        '200':
          description: The deleted widget.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Widget'
        '404':
          $ref: '#/components/responses/NotFound'
        default:
          $ref: '#/components/responses/GeneralError'
