/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.21).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package masko.mirotest.widgetservice.api;

import masko.mirotest.widgetservice.api.model.Widget;
import masko.mirotest.widgetservice.api.model.WidgetCreate;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;

public interface WidgetsApi {

    @RequestMapping(value = "/widgets",
            produces = {"application/json"},
            method = RequestMethod.GET)
    ResponseEntity<List<Widget>> widgetsGet(@Valid @Min(0) @RequestParam(value = "skip", required = false, defaultValue = "0") Integer skip
            , @Valid @Min(1) @Max(500) @RequestParam(value = "limit", required = false, defaultValue = "10") Integer limit);

    @RequestMapping(value = "/widgets/{id}",
            produces = {"application/json"},
            method = RequestMethod.DELETE)
    ResponseEntity<Widget> widgetsIdDelete(@PathVariable("id") Long id);

    @RequestMapping(value = "/widgets/{id}",
            produces = {"application/json"},
            method = RequestMethod.GET)
    ResponseEntity<Widget> widgetsIdGet(@PathVariable("id") Long id);

    @RequestMapping(value = "/widgets",
            produces = {"application/json"},
            consumes = {"application/json"},
            method = RequestMethod.POST)
    ResponseEntity<Widget> widgetsPost(@Valid @RequestBody WidgetCreate widget);

    @RequestMapping(value = "/widgets/{id}",
            produces = {"application/json"},
            consumes = {"application/json"},
            method = RequestMethod.PUT)
    ResponseEntity<Widget> widgetsIdPut(@PathVariable("id") Long id, @Valid @RequestBody WidgetCreate widget);

}

